Test evidence
biometricITC/cPP-toolboxes pull request #57
Opened 2022-06-27 13:35 UTC by woodbe

Adding a section about the visual recording of data since it is not necessary to record (via photos or video) the production and use of each individual artefact.

This is to close #52

2022-06-28 03:55 UTC, n-kai requested changes
As described in A.5 "Scheme Responsibilities" of CEM, the scheme can determine what is required in ensuring that an evaluation was done sufficiently. Under JP scheme, the validators/certifiers normally attend the penetration testing if the lab has no experiences of penetration testing of mobile biometrics. We can rely on the lab after that if the lab could conduct a penetration testing without any problem at the first evaluation, assuming the lab can do the same thereafter. So we may not need video evidence.

But bio-PP is a PP module for MDFPP which was developed by NIAP. So if NIAP wants to see such video evidence, I am fine with the current text, but I recommend to replace 234-236 with; 

*As the testing described in the individual toolboxes encompasses the creation and presentation of a large number of artefacts, the report should provide sufficient information to ensure how the artefacts were created, presented and as applicable, stored (or retrieved from storage).*

*If the scheme provides a guidance on the level of detail of the report, the evaluator needs to follow such guidance. However if there is no guidance available from the scheme, the BIO-iTC recommends to include pictures or video (visual) evidence in the report.*

*Broadly, visual evidence should be used on a per-artefact type basis, such that each type is shown clearly once, and the remainder of artefacts and usage would be recorded as expected.*

2022-06-28 12:17 UTC, woodbe commented
I have updated the text as suggested and moved it to 5.1.2. I also made a few other minor edits to the text given the new location.

2022-06-28 13:32 UTC, gregott commented
Visual evidence may not be sufficient if we get to voice or other PAD technologies that are not "seen".  Greg's suggestion of sufficient evidence to allow reproduction of artefacts is good.

2022-07-06 05:06 UTC, n-kai approved these changes

2022-07-12 14:07 UTC, merged