remove independent week
biometricITC/cPP-toolboxes pull request #59
Opened 2022-06-28 20:36 UTC by woodbe

remove one week timeline for independent testing

2022-07-06 05:24 UTC, n-kai requested changes
Following text in [BIOSD] should also be changed.

_7.3.1.4. Conduct the penetration testing_

_In order to place bounds on the effort involved related to the attack potential calculations for PAD functionality, **the independent and penetration testing** is expected to be finished within a single week, considering the assurance level claimed by [BIOPP-Module]._

2022-07-11 18:17 UTC, woodbe commented
@n-kai I created biometricITC/cPP-biometrics#390 to address the mismatch.

2022-07-12 04:55 UTC, n-kai approved these changes

2022-07-12 13:19 UTC, gfiumara approved these changes

2022-07-12 13:49 UTC, gregott approved these changes

2022-07-12 14:08 UTC, merged